# Config file for automatic testing at travis-ci.org
# To connect a new edX repository to Travis, see
# https://openedx.atlassian.net/wiki/spaces/EdxOps/pages/157464369/How+to+connect+a+repository+to+Travis+CI
#
# Be sure to change the Travis settings in the web UI to enable both
# "Build pushed branches" and "Build pushed pull requests".

language: python

python:
  - 3.5
  - 3.8

env:
  - TOXENV=django22
  - TOXENV=django30

matrix:
  include:
    - python: 3.5
      env: TOXENV=quality
    - python: 3.5
      env: TOXENV=docs
    - python: 3.5
      env: TOXENV=pii_check
  exclude:
    - python: 3.5
      env: TOXENV=django30

cache:
  - pip

before_install:
  - pip install --upgrade pip

install:
  - pip install -r requirements/travis.txt

script:
  - tox

after_success:
  - codecov

# Set token via "travis encrypt --add deploy.password"; for details, see
# https://docs.travis-ci.com/user/deployment/pypi
deploy:
  provider: pypi
  user: "__token__"
  distributions: sdist bdist_wheel
  password:
    secure: "UYM1MBTVMNHXjMCncBtlQ0j/Mt1V4HPc9L+x5kxneRWp8rBs/+3LBWz4RVIIRFENGO1uV9XfFZrnyWnjQakeA2bfDUQJwdCyIkkgXWIRukEk60/Y6OX78EjqWH/4Xt/YlLXq+/igXa5qljtofOjrTVYJVBEE8Ar8bUhH9tlZQyev9ARVyylqlZXztxiKCoqy3sXCU7SawB1HQnMfj/L2/gk+Lg9Dpu4Vb8JYar0/vyXfUoxWV66QEEjd6KVwvCqS55nIg8c/cOvOpxd+Xo3KLutq6eob3cqKDaCIJpPCA0tVbTv8jhv/Re78kyDSXVMT91YWxtOVQgSQhe6QsOeiKWVwRzHAV7yooGwcTS7bfa7gltvKqSlY5upcY4W+AXVXwr3+nsmSfZFlrjhcfYVFA+NiTd3puoAuzBWpkt/BD1bqWDCLOzFFfJsHLA2jQ2GfySuRT2VDlJIKhESKS8BhxjAFkaBvMm1RvMUt9hEFfeb8O6ykxZ91O6mdd+/m7aPzschRpUFDp4yRXcZfN8Oi0BHB7dti9mypCibwMSKvTCWFfH6xzCWuzmz1bUTlW//xhx7dComOmwtB60slTuTBy0rfLQ7YBvPWjwr4/lkcPgWbWWD86CiSN2nUaiVfdbUPwAkGd6phA+XMKgZmpKjonSyJR28uj3bvACzY09FAleE="
  on:
    tags: true
    condition: '$TOXENV = quality'
