# Generated by Django 2.2.19 on 2021-03-01 05:18

from django.db import migrations

import event_routing_backends.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('event_routing_backends', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routerconfiguration',
            name='configurations',
            field=event_routing_backends.utils.fields.EncryptedJSONField(),
        ),
    ]
